### ISSUE TITLE
Change discus account on quanteda.org

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#1]
Currently it's set to quanteda.io - maybe this is just a naming thing?

**Comment by kbenoit** [comment]
They are both set now to account "quanteda.io", but probably would be better described as quanteda or quanteda.org. Can we easily change this for both the news and the blog sites?

**Comment by amatsuo** [comment]
I'm a bit confused. Where can you see quanteda.io? Or is it already fixed?

<img width="1279" alt="screen shot 2018-09-25 at 7 12 48 am" src="https://user-images.githubusercontent.com/8436792/45996055-a2917500-c092-11e8-8606-95273d6cb5e3.png">

**Comment by kbenoit** [comment]
It's the same account on blog.quanteda.org and quanteda.org (News), namely:
https://www.dropbox.com/s/udgw2w8aiuiqfj5/Screenshot%202018-09-25%2008.42.20.png?dl=0

But worth verifying that this is the one we want. Maybe call it QI?
