### ISSUE TITLE
Fix font sizes and spacing

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#15]
The text looks squashed for the descriptions, the blog entries, and the About page. (Probably all part of the same style). Some combination needed of smaller font and larger line spacing.

**Comment by stefan-mueller** [comment]
I agree and would propose to 
- slightly increase the font size of the menu items (Home, About etc.) and
- make sure that the numbers in numbered lists have the same font size as the text (see "Objectives" under "About").
