### ISSUE TITLE
Publish the new website

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#17]
(after #15, #14, and #13 are closed)

- [ ] deactivate the current "quanteda landing page" at https://quanteda.io
- [ ] redirect https://quanteda.io to http://docs.quanteda.io/index.html, and make this the main reference URL for accessing this page, with the docs.quanteda.io kept only for legacy purposes
- [ ] change the current https://quanteda-org.netlify.com to https://quanteda.org
- [ ] fix any broken links that pointed to the netlify site
- [ ] change the Netlify account to a Quanteda Initiative account - it is currently linked to @koheiw 's account

**Comment by koheiw** [comment]
In order to do that, please 
- make quanteda.io under my control in Name Cheap (no sharing your account info with me)
- delete Name Cheap web server

**Comment by kbenoit** [comment]
Moved to #26 and #25
