### ISSUE TITLE
Make badges appear consistently on sides of pkgdown websites

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#23]
Currently, only the **readtext** pkgdown site https://stopwords.quanteda.io shows its badges on the sidebar. 

We want the following sites to look the same:
- [ ] **spacyr** http://spacyr.quanteda.io
- [ ] **readtext** http://readtext.quanteda.io

**Comment by amatsuo** [comment]
I will look into it. 

But, I'm not familiar with the way these websites are constructed. Are they generated locally? And how?

**Comment by kbenoit** [comment]
They are generated at the package repo level, by running `pkgdown::build_site()`. The `README.(R)md` or `index.md` becomes the root page `index.html` for the pkgdown site. 

See https://pkgdown.r-lib.org/articles/pkgdown.html#home-page

**Comment by amatsuo** [comment]
Thanks. Will do now.
