### ISSUE TITLE
Switch Netlify to new website and new account

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#25]
- The previous sandbox URL https://quanteda-org.netlify.com should be deactivated, and Netlify should simply reply the Hugo repo to https://quanteda.org.

- Netlify account should be changed to the QI Netlify account. @koheiw I have sent you the access details separately.

**Comment by koheiw** [comment]
Did you create a Netlify Team Pro account? Otherwise, I will just as you to my Personal (free) account.

**Comment by kbenoit** [comment]
No I created a personal one for admin@quanteda.org<mailto:admin@quanteda.org>. Should we create a team account? Might need more money in the QI account first!

Sent from my iPhone

On 22 Sep 2018, at 17:53, Kohei Watanabe <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you create a Netlify Team Pro account? Otherwise, I will just as you to my Personal (free) account.

**Comment by koheiw** [comment]
Let's keep it as is because we no longer use Netlify's DNS sever extensively. Extra personal account causes me a lot of trouble.
