### ISSUE TITLE
https://docs.quanteda.io not working

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#33]
All the URLs are working including http://docs.quanteda.io pointing to https://quanteda.io, _except_ that https://docs.quanteda.io/ does not point to anything. 

@koheiw has contacted Namecheap about this but their answer was rather cryptic. It has to do with SSL certificates.

Can this be resolved in some way, either via Namecheap or some other solution>

**Comment by koheiw** [comment]
Only way to solve this is setting up a web server with SSL that redirect all the traffic. I don't think it is worth doing. People will just Google and find the new website.

**Comment by kbenoit** [comment]
OK, so we just have to make sure that there are no more links, anywhere, to https://docs.quanteda.io.  @stefan-mueller have you checked the tutorial site?

**Comment by stefan-mueller** [comment]
I checked the following repos: 

- **quanteda**: There are still a [couple of occurrences](https://github.com/quanteda/quanteda/search?p=1&q=%22docs.quanteda%22&unscoped_q=%22docs.quanteda%22), and I will change them in a separate PR. 
- **readtext**: no occurrences of `docs.quanteda.io`
- **spacyr**: no occurrences of `docs.quanteda.io`
- **stopwords**: no occurrences of `docs.quanteda.io`
- **quantda_tutorial**:  I updated all URLs in [this branch](https://github.com/quanteda/quanteda_tutorials/compare/update-links) which needs to be double-checked by @koheiw first.

**Comment by koheiw** [comment]
I renamed tutorials to `tutorials.quanteda.id`, but I cannot rebuild the website until https://github.com/quanteda/quanteda/pull/1441 is merged.

**Comment by kbenoit** [comment]
https://github.com/quanteda/quanteda/pull/1441 merged now.
