### ISSUE TITLE
Expand activity of social media (Twitter) to promote quanteda and the QI

### ISSUE THREAD

**Issue by stefan-mueller** [quanteda/quanteda.org#47]
If we get the QI blog started and want to inform people about new package releases, blog posts, and publications that use **quanteda**, we might think about extending the activities on social media, especially Twitter. 

Currently, @kbenoit administers the account "textasdata", but I am not sure whether this account is supposed to be used for QI-related news. 

I figured out that a "quanteda" Twitter account already exists (did one of you create this one?), and that "quantedainitiative" is too long (usernames must be shorter than 15 characters).

If we want to be more active on Twitter, I guess we have four options:
1. Use the "textasdata" account.
2. Use the "quanteda" account (if one of you owns it).
3. Create a new account (not sure about the name though).
4. Use our personal accounts only.

Just wanted to raise this question, let me know what you think.

**Comment by kbenoit** [comment]
I have set up @quantedainit, see your email @stefan-mueller. I am also trying to get @quanteda but it's already owned so I have a few additional hurdles to clear first.
