### ISSUE TITLE
Devise categories for News

### ISSUE THREAD

**Issue by kbenoit** [quanteda/quanteda.org#6]
How about:

* Packages (software updates)
* Training (for training and educational events specifically)
* Events (workshops and conferences not aimed at training)
* Organisational (for company-related changes, e.g. personnel, funding partnerships, etc.)
* Misc (anything else - or should we omit this?)

**Comment by kbenoit** [comment]
@koheiw what do you think of the categories?

**Comment by kbenoit** [comment]
I went ahead and updated the taxonomies in the config.toml and added appropriate tags/categories/packages to each News post. This includes a custom label called "packages". 

Would be nice to be able to add packages to the sidebar (see https://github.com/quanteda/quanteda.org/blob/master/themes/quanteda/layouts/partials/sidebar.html).

**Comment by ciflikli** [comment]
PR https://github.com/quanteda/quanteda.org/pull/12
